// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuoajnexomtyqsabanqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1b2FqbmV4b210eXFzYWJhbnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTczODUsImV4cCI6MjA2MzU3MzM4NX0.LF_jIrxx_dxXtwRysa6uS6z_-4JiqxtUWOk2CAX0nUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);